<a href="https://colab.research.google.com/github/Snehamn24/python-numpy-module/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In numpy we can create the ndarray - n-dimensional array we have to pass either the tuple or the list to create the ndarray we use it for storing the matrices , vectors and tensors

In [4]:
import numpy as np

#we have to use array method
arr1 = np.array(40) #0-dimension
arr2 = np.array([10,20]) #1-dimension array
arr3 = np.array([[10,20],[30,40]]) #2-dimensional array
print(arr1)
print(arr2)
print(arr3)
print(type(arr1))


40
[10 20]
[[10 20]
 [30 40]]
<class 'numpy.ndarray'>


In [7]:
#zeroes and ones in the numpy

import numpy as np

arr1 = np.zeros(3)
print(arr1)

arr2 = np.zeros([3,4])
print(arr2)


[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 3-D array

In [10]:
import numpy as np

#3-d array is generally a array of 2-d arrays
arr = np.array([[[1,2],[3,4]]
                ,[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [12]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr.ndim)

1
2
2
3


In [13]:
#we can create the ndarray of many dimensions as we need using the ndim = dimesion
arr4 = np.array([1,2,3,4,5],ndmin=5)
print(arr4)
print(arr4.ndim)

[[[[[1 2 3 4 5]]]]]
5
